name: CI
on:
  - push
  - pull_request
jobs:
  x86_64-linux:
    runs-on: ubuntu-latest
    # We want to run on external PRs, but not on our own internal PRs as they'll be run by the push
    # to the branch.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    env:
      DISPLAY: ":99.0"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "true"
      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0
      - name: x86_64-linux -> x86_64-macos
        run: zig build -Dtarget=x86_64-macos
      - name: x86_64-linux -> aarch64-macos
        run: zig build -Dtarget=aarch64-macos
      - name: x86_64-linux -> x86_64-windows
        run: zig build -Dtarget=x86_64-windows
      - name: launch xvfb
        run: Xvfb :99 -screen 0 1680x720x24 > /dev/null 2>&1 &
      - name: build
        run: |
          sudo add-apt-repository -y ppa:kisak/kisak-mesa
          sudo apt-get update
          sudo apt-get install mesa-utils mesa-utils-extra mesa-va-drivers mesa-vdpau-drivers mesa-vulkan-drivers xvfb
          zig build
      # - name: test
      #   run: zig build test
  x86_64-windows:
    runs-on: windows-latest
    # We want to run on external PRs, but not on our own internal PRs as they'll be run by the push
    # to the branch.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "true"
      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0
      - name: x86_64-windows -> x86_64-macos
        run: zig build -Dtarget=x86_64-macos
      - name: x86_64-windows -> aarch64-macos
        run: zig build -Dtarget=aarch64-macos
      - name: x86_64-windows -> x86_64-linux
        run: zig build -Dtarget=x86_64-linux
      - name: build
        run: zig build
      # - name: test
      #   run: zig build test
  x86_64-macos:
    runs-on: macos-13
    # We want to run on external PRs, but not on our own internal PRs as they'll be run by the push
    # to the branch.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "true"
      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0
      - name: x86_64-macos -> aarch64-macos
        run: zig build -Dtarget=aarch64-macos
      - name: x86_64-macos -> x86_64-windows
        run: zig build -Dtarget=x86_64-windows
      - name: x86_64-macos -> x86_64-linux
        run: zig build -Dtarget=x86_64-linux
      - name: build
        run: zig build
      # - name: test
      #   run: zig build test
  aarch64-macos:
    runs-on: macos-latest
    # We want to run on external PRs, but not on our own internal PRs as they'll be run by the push
    # to the branch.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "true"
      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0
      - name: aarch64-macos -> x86_64-macos
        run: zig build -Dtarget=x86_64-macos
      - name: aarch64-macos -> x86_64-windows
        run: zig build -Dtarget=x86_64-windows
      - name: aarch64-macos -> x86_64-linux
        run: zig build -Dtarget=x86_64-linux
      - name: build
        run: zig build
      # - name: test
      #   run: zig build test
